import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "../globals.css";
import Menubar from "@/components/spotify/menubar";
import SideMenu from "@/components/spotify/sideMenu";
import NowPlaying from "@/components/spotify/nowplaying";
import Friends from "@/components/activities/useractivities";
import React from "react";
import localFont from "next/font/local";
import ActivitiesList from "@/components/activities/activitieslist";
const inter = Inter({ subsets: ["latin"], variable: "--inter-font" });
const myFont = localFont({
    src: [
        {
            path: "../../../public/fonts/Satoshi-regular.woff2",
            style: "normal",
            weight: "400",
        },
        {
            path: "../../../public/fonts/Satoshi-Medium.woff2",
            style: "normal",
            weight: "500",
        },
        {
            path: "../../../public/fonts/Satoshi-Bold.woff2",
            style: "normal",
            weight: "700",
        },
        {
            path: "../../../public/fonts/Satoshi-black.woff2",
            style: "normal",
            weight: "900",
        },
    ],
});
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="grid grid-cols-[227px,_auto] grid-rows-[54px,_calc(100vh_-_(calc(81px_+_54px))),_81px] bg-mainBackground">
            <Menubar />
            <SideMenu />
            <div className="col-[2/-1] row-[2/3]  overflow-scroll hide-scroll grid grid-cols-[1fr,_auto] gap-[5px] auto-rows-auto">
                {children}
                <Friends>
                    <ActivitiesList />
                </Friends>
            </div>
            <NowPlaying />
        </main>
    );
}
