"use client";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "../globals.css";
import Menubar from "@/components/spotify/menubar";
import SideMenu from "@/components/spotify/sideMenu";
import NowPlaying from "@/components/spotify/nowplaying";
import Friends from "@/components/spotify/friends";
import React from "react";
import { useSpotifyContext } from "@/utils/store/store";
import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"], variable: "--inter-font" });
const myFont = localFont({
    src: [
        {
            path: "../../../public/fonts/Satoshi-regular.woff2",
            style: "normal",
            weight: "400",
        },
        {
            path: "../../../public/fonts/Satoshi-Medium.woff2",
            style: "normal",
            weight: "500",
        },
        {
            path: "../../../public/fonts/Satoshi-Bold.woff2",
            style: "normal",
            weight: "700",
        },
        {
            path: "../../../public/fonts/Satoshi-black.woff2",
            style: "normal",
            weight: "900",
        },
    ],
});
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const toOpenFriendTab = useSpotifyContext((prev) => prev.isFriendsTabOpen);
    return (
        <html lang="en">
            <body className={`${myFont.className} bg-mainBackground`}>
                <SessionProvider>
                    <div className="grid grid-cols-[227px,_auto] grid-rows-[54px,_calc(100vh_-_(calc(81px_+_54px))),_81px] bg-mainBackground">
                        <Menubar />
                        <SideMenu />
                        <div className="col-[2/-1] row-[2/3]  overflow-scroll hide-scroll grid grid-cols-[1fr,_auto] gap-[5px] auto-rows-auto">
                            {children}
                            {toOpenFriendTab && <Friends />}
                        </div>
                        <NowPlaying />
                    </div>
                </SessionProvider>
            </body>
        </html>
    );
}
