import HomeMenu from "@/components/pages/home/homemenu";
import HomePlaylists from "@/components/pages/home/homeplaylists";
import Friends from "@/components/spotify/friends";
import PlaylistCard from "@/components/spotify/playlistCard";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function Page() {
    return (
        <div className="border rounded-[10px] border-secondaryBackground overflow-scroll hide-scroll">
            <HomeMenu />
            <div className="mx-[25px] mt-[15px] min-h-screen flex flex-col gap-[11px]">
                <HomePlaylists length={14} variant="artiste" />
                <HomePlaylists length={10} variant="album" />
                <HomePlaylists length={10} variant="playlist" />
            </div>
        </div>
    );
}

export default Page;
